[package]
name = "dnd"
version = "0.1.0"
authors = ["Trevor Wilson <kmdreko@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta"
tracing = "0.1.26"
tracing-actix-web = "0.4.0-beta"
tracing-subscriber = "0.2.18"
tokio = { version = "1.6.0", features = ["full"] }
